import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { MapPin, Plus, Search } from "lucide-react";
import { useState } from "react";
import { BottomSheet, CrestSheet, CrestTile, FormLabel, ProgressDashes, RegistrationShell, ScreenHeading } from "@/components/registration/registration-ui";
import { PrimaryButton } from "@/components/ip/primitives";
import { clubMonogram, useRegistration } from "@/store/registration-store";

export const Route = createFileRoute("/signup/club")({ head: () => ({ meta: [{ title: "Your club — Ipanema" }, { name: "description", content: "Add your club identity and home ground to Ipanema." }, { property: "og:title", content: "Your club — Ipanema" }, { property: "og:description", content: "Add your club identity and home ground." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ClubRegistration });
const grounds = [{ name: "Norrviken IP", place: "Sollentuna, Sweden" }, { name: "Sollentunavallen", place: "Sollentuna, Sweden" }, { name: "Skytteholms IP", place: "Solna, Sweden" }];
function ClubRegistration() {
 const navigate=useNavigate(); const data=useRegistration(); const [crestOpen,setCrestOpen]=useState(false); const [focused,setFocused]=useState(false); const monogram=clubMonogram(data.clubName); const valid=data.clubName.trim().length>=2 && data.crestMode!=="empty" && data.ground.trim().length>0;
 const selectCrest=(mode:"image"|"monogram",file?:File)=>{ if(file){const reader=new FileReader(); reader.onload=()=>data.set({crestMode:"image",crestImage:String(reader.result)}); reader.readAsDataURL(file);} else data.set({crestMode:"monogram",crestImage:null}); setCrestOpen(false); };
 return <RegistrationShell footer={<PrimaryButton block disabled={!valid} onClick={()=>navigate({to:"/signup/team"})} className="min-h-[54px] rounded-[14px] text-[15px] disabled:bg-surface-3 disabled:text-text-faint disabled:opacity-100">Next</PrimaryButton>}><ProgressDashes step={1}/><ScreenHeading title="Your club" sub="Two steps, then your first match."/><div className="mt-7 flex flex-col items-center"><CrestTile monogram={monogram} colour={data.kitColour} image={data.crestImage} empty={data.crestMode==="empty"} onClick={()=>setCrestOpen(true)}/><p className="mt-3 text-[11px] text-text-faint">Shown on reels and session plans</p></div><div className="mt-7 space-y-5"><label className="block"><FormLabel>Club name</FormLabel><input className="tap w-full rounded-xl border-[1.5px] border-wire bg-surface px-4 text-[15px] text-text focus:border-cream/60" value={data.clubName} onChange={e=>{ const clubName=e.target.value; data.set({clubName, crestMode:data.crestMode==="empty" && clubName.trim() ? "monogram":data.crestMode}); }} aria-label="Club name"/><span className="mt-1.5 block text-[11.5px] text-text-faint">On every match and shared reel</span></label><div className="relative"><FormLabel>Home ground</FormLabel><Search size={16} className="pointer-events-none absolute left-3.5 top-[40px] text-text-faint"/><input className="tap w-full rounded-xl border-[1.5px] border-wire bg-surface pl-10 pr-4 text-[15px] text-text placeholder:text-text-faint focus:border-cream/60" value={data.ground} onFocus={()=>setFocused(true)} onBlur={()=>setTimeout(()=>setFocused(false),120)} onChange={e=>data.set({ground:e.target.value})} placeholder="Search for your ground" aria-label="Home ground"/><span className="mt-1.5 block text-[11.5px] text-text-faint">Tags home and away matches</span>{focused && <div className="absolute z-20 mt-2 w-full overflow-hidden rounded-xl border-[1.5px] border-wire bg-surface">{grounds.filter(g=>g.name.toLowerCase().includes(data.ground.toLowerCase())).map(g=><button type="button" key={g.name} onMouseDown={()=>data.set({ground:g.name,country:"Sweden"})} className="tap flex w-full items-center gap-3 border-b border-wire-2 px-4 py-3 text-left"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-surface-2 text-text-faint"><MapPin size={12}/></span><span><strong className="block text-[14px] font-semibold text-text">{g.name}</strong><small className="text-[11.5px] text-text-faint">{g.place}</small></span></button>)}<button type="button" onMouseDown={()=>setFocused(false)} className="tap flex w-full items-center gap-3 px-4 py-3 text-left"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-surface-2 text-text-faint"><Plus size={12}/></span><span className="text-[14px] italic text-text-dim">Use “{data.ground || "your ground"}”</span></button></div>}</div></div><CrestSheet open={crestOpen} onClose={()=>setCrestOpen(false)} onSelect={selectCrest}/></RegistrationShell>;
}
