import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { usePendingUpload } from "@/store/upload-store";
import { uploadMatch, type UploadProgress } from "@/lib/upload";
import { matchesDb } from "@/integrations/matches/client";
import { Wordmark, PrimaryButton, GhostButton } from "@/components/ip/primitives";
import { MatchBuild, Pipeline, PitchTracker, ProgressRing } from "@/components/registration/processing-visuals";
type Status="running"|"failed"|"complete";
export const Route=createFileRoute("/upload_/processing")({validateSearch:(s:Record<string,unknown>)=>({progress:typeof s["progress"]==="number"?s["progress"]:typeof s["progress"]==="string"?Number(s["progress"]):undefined,stage:typeof s["stage"]==="number"?s["stage"]:typeof s["stage"]==="string"?Number(s["stage"]):undefined,status:(s["status"]==="failed"||s["status"]==="complete"?s["status"]:"running") as Status,fixed:s["fixed"]===true||s["fixed"]==="true",id:typeof s["id"]==="string"?s["id"]:undefined}),head:()=>({meta:[{title:"Analysing your match — Ipanema"},{name:"description",content:"Follow upload and football analysis progress."},{property:"og:title",content:"Analysing your match — Ipanema"},{property:"og:description",content:"Your match analysis is underway."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Processing});
function Processing(){const nav=useNavigate();const search=Route.useSearch();const pending=usePendingUpload();const [progress,setProgress]=useState(Math.max(0,Math.min(100,search.progress??0)));const [status,setStatus]=useState<Status>(search.status);const [matchId,setMatchId]=useState<string|undefined>(search.id);const [up,setUp]=useState<UploadProgress|null>(null);const [error,setError]=useState<string|null>(null);const [dbStatus,setDbStatus]=useState<string|null>(null);type Prog={stage:number;label:string;pct:number;elapsed_s:number;eta_s:number|null;updated_at:string;scope?:string;segment_ready?:string;error?:boolean};const [prog,setProg]=useState<Prog|null>(null);const [createdAt,setCreatedAt]=useState<string|null>(null);const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(t)},[]);const startedRef=useRef(false);const forcedStage=search.stage;const demo=search.fixed;
/* 1) real upload: fills the first fifth of the ring */
useEffect(()=>{if(demo||matchId||startedRef.current)return;const file=pending.file,meta=pending.meta;if(!file||!meta){setStatus("failed");setError("Choose the match video again to start the upload.");return}startedRef.current=true;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",warn);uploadMatch(file,meta,p=>{setUp(p);setProgress(Math.min(19,Math.floor(p.sentBytes/Math.max(p.totalBytes,1)*19)))}).then(r=>{pending.clear();setMatchId(r.match_id);setProgress(20);nav({to:"/upload/processing",search:{progress:20,stage:1,status:"running",fixed:false,id:r.match_id},replace:true})}).catch(e=>{setStatus("failed");setError(e instanceof Error?e.message:"The upload stopped.")}).finally(()=>window.removeEventListener("beforeunload",warn))},[demo,matchId]);
/* 2) real analysis status from the database */
useEffect(()=>{if(demo||!matchId)return;let alive=true;const poll=async()=>{const {data}=await matchesDb.from("matches").select("status,summary,created_at").eq("id",matchId).maybeSingle();if(!alive||!data)return;const row=data as {status:string;summary:{progress?:Prog}|null;created_at:string};const st=String(row.status);setDbStatus(st);setCreatedAt(row.created_at);setProg(row.summary?.progress??null);if(st==="ready"){setProgress(100);setStatus("complete")}else if(st==="failed"){setStatus("failed");setError("We couldn't analyse this match. The video is safely stored — we'll look into it.")}else setProgress(p=>Math.max(p,25))};void poll();const t=window.setInterval(poll,10000);return()=>{alive=false;window.clearInterval(t)}},[demo,matchId]);
/* design previews (?fixed / demo links) keep the original simulation */
useEffect(()=>{if(!demo||status!=="running")return;const timer=window.setInterval(()=>setProgress(p=>{const next=Math.min(100,p+5);if(next===100)setStatus("complete");return next}),1400);return()=>window.clearInterval(timer)},[demo,status]);
const stage=forcedStage!==undefined&&demo?Math.max(0,Math.min(4,forcedStage)):Math.min(4,Math.floor(progress/20));const mins=Math.max(1,Math.ceil((100-progress)/25));const mb=(b:number)=>(b/1024/1024).toFixed(0);const eta=up&&up.bytesPerSec>0?(up.totalBytes-up.sentBytes)/up.bytesPerSec:null;
const clock=(sec:number)=>sec>=3600?`${Math.floor(sec/3600)} h ${Math.round(sec%3600/60)} min`:sec>=60?`${Math.round(sec/60)} min`:`${Math.max(0,Math.round(sec))} s`;const sinceUpdate=prog?Math.max(0,(now-Date.parse(prog.updated_at))/1000):0;const running=prog?prog.elapsed_s+sinceUpdate:0;const left=prog&&prog.eta_s!==null?Math.max(0,prog.eta_s-sinceUpdate):null;const waited=createdAt?Math.max(0,(now-Date.parse(createdAt))/1000):0;const segmentReady=prog?.segment_ready;
const headline=demo?(progress<20?"Uploading — about 1 minute":`About ${mins} ${mins===1?"minute":"minutes"} remaining`):!matchId?(up?`Uploading · ${Math.floor(up.sentBytes/Math.max(up.totalBytes,1)*100)}% · ${mb(up.sentBytes)} of ${mb(up.totalBytes)} MB`:"Preparing upload…"):dbStatus==="ready"?"Ready":segmentReady?"Your 5-minute test is ready":prog?`${prog.label} · ${prog.pct}%`:"Waiting for the pitch setup";
const subline=demo?"We'll notify you when it's ready.":!matchId?(eta===null?"Keep this page open until the upload finishes.":eta>3600?`About ${Math.round(eta/3600)} h left · keep this page open`:eta>90?`About ${Math.round(eta/60)} min left · keep this page open`:"Almost done · keep this page open"):segmentReady?"The full match follows once full-match analysis is switched on.":prog?`${prog.scope==="5-minute test"?"5-minute test · ":""}running for ${clock(running)}${left!==null?` · about ${clock(left)} left`:""}`:`Uploaded ${clock(waited)} ago · the first match at a new ground needs its pitch set up once. After that, matches here analyse automatically.`;
return <main className="registration-theme flex min-h-[100svh] flex-col items-center bg-bg px-6 py-6 text-center"><Wordmark size="sm" className="opacity-40"/><p className="mt-4 text-[14px] text-text-dim">Analysing your match</p><div className="flex flex-1 flex-col items-center justify-center py-8">{demo?<ProgressRing progress={progress} status={status}/>:<MatchBuild phase={!matchId?-1:dbStatus==="ready"?4:prog?prog.stage:0} pct={up?Math.floor(up.sentBytes/Math.max(up.totalBytes,1)*100):0} status={status}/>}{status==="running"?<><p className="mt-7 text-[14px] font-semibold text-text">{headline}</p><p className="mt-1 max-w-[340px] text-[11.5px] text-text-faint">{subline}</p><div className="mt-7"><Pipeline stage={demo?stage:!matchId?-1:prog?prog.stage:0}/></div>{demo&&<div className="mt-7"><PitchTracker stage={stage}/></div>}</>:status==="failed"?<div className="mt-7 max-w-[420px]"><h1 className="display-i text-[30px] text-text">{matchId?"We couldn't process this match.":"The upload stopped."}</h1><p className="mt-2 text-[13px] leading-relaxed text-text-dim">{error??"Something went wrong."}</p><div className="mt-5 grid gap-2"><PrimaryButton className="h-12 rounded-xl" onClick={()=>{if(demo){setProgress(0);setStatus("running");return}nav({to:"/upload"})}}>{demo?"Retry":"Try again"}</PrimaryButton><GhostButton className="h-12" onClick={()=>nav({to:"/upload"})}>Choose another file</GhostButton></div></div>:<div className="mt-7"><h1 className="display-i text-[30px] text-text">Ready to review.</h1><PrimaryButton className="mt-5 h-12 rounded-xl" onClick={()=>matchId?nav({to:"/match/$matchId/insights",params:{matchId}}):nav({to:"/library"})}>Open the analysis →</PrimaryButton></div>}</div>{status==="running"&&segmentReady&&<PrimaryButton className="mb-3 h-12 rounded-xl" onClick={()=>nav({to:"/match/$matchId/insights",params:{matchId:segmentReady}})}>Open the 5-minute test →</PrimaryButton>}{status==="running"&&(demo||matchId)&&<GhostButton className="text-[12.5px]" onClick={()=>nav({to:"/library"})}>Hide and finish later</GhostButton>}</main>}
