/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProcessingRouteImport } from './routes/_authenticated/processing'
import { Route as SignupClubRouteImport } from './routes/signup_.club'
import { Route as SignupReadyRouteImport } from './routes/signup_.ready'
import { Route as SignupTeamRouteImport } from './routes/signup_.team'
import { Route as UploadProcessingRouteImport } from './routes/upload_.processing'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedSettingsClubRouteImport } from './routes/_authenticated/settings.club'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as SPlayerTokenRouteImport } from './routes/s.player.$token'
import { Route as SReelTokenRouteImport } from './routes/s.reel.$token'
import { Route as AuthenticatedMatchMatchIdInsightsRouteImport } from './routes/_authenticated/match.$matchId.insights'
import { Route as AuthenticatedMatchMatchIdMatchRouteImport } from './routes/_authenticated/match.$matchId.match'
import { Route as AuthenticatedMatchMatchIdReelRouteImport } from './routes/_authenticated/match.$matchId.reel'
import { Route as AuthenticatedMatchMatchIdSessionRouteImport } from './routes/_authenticated/match.$matchId.session'
import { Route as AuthenticatedMatchMatchIdStatsRouteImport } from './routes/_authenticated/match.$matchId.stats'
import { Route as AuthenticatedMatchMatchIdStoryRouteImport } from './routes/_authenticated/match.$matchId.story'
import { Route as AuthenticatedMatchMatchIdTerritoryRouteImport } from './routes/_authenticated/match.$matchId.territory'
import { Route as AuthenticatedMatchMatchIdPlayerPlayerIdRouteImport } from './routes/_authenticated/match.$matchId.player.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessingRoute = AuthenticatedProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SignupClubRoute = SignupClubRouteImport.update({
  id: '/signup_/club',
  path: '/signup/club',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupReadyRoute = SignupReadyRouteImport.update({
  id: '/signup_/ready',
  path: '/signup/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupTeamRoute = SignupTeamRouteImport.update({
  id: '/signup_/team',
  path: '/signup/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProcessingRoute = UploadProcessingRouteImport.update({
  id: '/upload_/processing',
  path: '/upload/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsClubRoute =
  AuthenticatedSettingsClubRouteImport.update({
    id: '/settings/club',
    path: '/settings/club',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SPlayerTokenRoute = SPlayerTokenRouteImport.update({
  id: '/s/player/$token',
  path: '/s/player/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SReelTokenRoute = SReelTokenRouteImport.update({
  id: '/s/reel/$token',
  path: '/s/reel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMatchMatchIdInsightsRoute =
  AuthenticatedMatchMatchIdInsightsRouteImport.update({
    id: '/match/$matchId/insights',
    path: '/match/$matchId/insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdMatchRoute =
  AuthenticatedMatchMatchIdMatchRouteImport.update({
    id: '/match/$matchId/match',
    path: '/match/$matchId/match',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdReelRoute =
  AuthenticatedMatchMatchIdReelRouteImport.update({
    id: '/match/$matchId/reel',
    path: '/match/$matchId/reel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdSessionRoute =
  AuthenticatedMatchMatchIdSessionRouteImport.update({
    id: '/match/$matchId/session',
    path: '/match/$matchId/session',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdStatsRoute =
  AuthenticatedMatchMatchIdStatsRouteImport.update({
    id: '/match/$matchId/stats',
    path: '/match/$matchId/stats',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdStoryRoute =
  AuthenticatedMatchMatchIdStoryRouteImport.update({
    id: '/match/$matchId/story',
    path: '/match/$matchId/story',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdTerritoryRoute =
  AuthenticatedMatchMatchIdTerritoryRouteImport.update({
    id: '/match/$matchId/territory',
    path: '/match/$matchId/territory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchMatchIdPlayerPlayerIdRoute =
  AuthenticatedMatchMatchIdPlayerPlayerIdRouteImport.update({
    id: '/match/$matchId/player/$playerId',
    path: '/match/$matchId/player/$playerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new': typeof AuthenticatedNewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/signup/club': typeof SignupClubRoute
  '/signup/ready': typeof SignupReadyRoute
  '/signup/team': typeof SignupTeamRoute
  '/upload/processing': typeof UploadProcessingRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/club': typeof AuthenticatedSettingsClubRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/s/player/$token': typeof SPlayerTokenRoute
  '/s/reel/$token': typeof SReelTokenRoute
  '/match/$matchId/insights': typeof AuthenticatedMatchMatchIdInsightsRoute
  '/match/$matchId/match': typeof AuthenticatedMatchMatchIdMatchRoute
  '/match/$matchId/reel': typeof AuthenticatedMatchMatchIdReelRoute
  '/match/$matchId/session': typeof AuthenticatedMatchMatchIdSessionRoute
  '/match/$matchId/stats': typeof AuthenticatedMatchMatchIdStatsRoute
  '/match/$matchId/story': typeof AuthenticatedMatchMatchIdStoryRoute
  '/match/$matchId/territory': typeof AuthenticatedMatchMatchIdTerritoryRoute
  '/match/$matchId/player/$playerId': typeof AuthenticatedMatchMatchIdPlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glossary': typeof GlossaryRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new': typeof AuthenticatedNewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/processing': typeof AuthenticatedProcessingRoute
  '/signup/club': typeof SignupClubRoute
  '/signup/ready': typeof SignupReadyRoute
  '/signup/team': typeof SignupTeamRoute
  '/upload/processing': typeof UploadProcessingRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/club': typeof AuthenticatedSettingsClubRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/s/player/$token': typeof SPlayerTokenRoute
  '/s/reel/$token': typeof SReelTokenRoute
  '/match/$matchId/insights': typeof AuthenticatedMatchMatchIdInsightsRoute
  '/match/$matchId/match': typeof AuthenticatedMatchMatchIdMatchRoute
  '/match/$matchId/reel': typeof AuthenticatedMatchMatchIdReelRoute
  '/match/$matchId/session': typeof AuthenticatedMatchMatchIdSessionRoute
  '/match/$matchId/stats': typeof AuthenticatedMatchMatchIdStatsRoute
  '/match/$matchId/story': typeof AuthenticatedMatchMatchIdStoryRoute
  '/match/$matchId/territory': typeof AuthenticatedMatchMatchIdTerritoryRoute
  '/match/$matchId/player/$playerId': typeof AuthenticatedMatchMatchIdPlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/glossary': typeof GlossaryRoute
  '/reset': typeof ResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/processing': typeof AuthenticatedProcessingRoute
  '/signup_/club': typeof SignupClubRoute
  '/signup_/ready': typeof SignupReadyRoute
  '/signup_/team': typeof SignupTeamRoute
  '/upload_/processing': typeof UploadProcessingRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/club': typeof AuthenticatedSettingsClubRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/s/player/$token': typeof SPlayerTokenRoute
  '/s/reel/$token': typeof SReelTokenRoute
  '/_authenticated/match/$matchId/insights': typeof AuthenticatedMatchMatchIdInsightsRoute
  '/_authenticated/match/$matchId/match': typeof AuthenticatedMatchMatchIdMatchRoute
  '/_authenticated/match/$matchId/reel': typeof AuthenticatedMatchMatchIdReelRoute
  '/_authenticated/match/$matchId/session': typeof AuthenticatedMatchMatchIdSessionRoute
  '/_authenticated/match/$matchId/stats': typeof AuthenticatedMatchMatchIdStatsRoute
  '/_authenticated/match/$matchId/story': typeof AuthenticatedMatchMatchIdStoryRoute
  '/_authenticated/match/$matchId/territory': typeof AuthenticatedMatchMatchIdTerritoryRoute
  '/_authenticated/match/$matchId/player/$playerId': typeof AuthenticatedMatchMatchIdPlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/glossary'
    | '/reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/upload'
    | '/library'
    | '/new'
    | '/onboarding'
    | '/processing'
    | '/signup/club'
    | '/signup/ready'
    | '/signup/team'
    | '/upload/processing'
    | '/settings/account'
    | '/settings/club'
    | '/settings/profile'
    | '/s/player/$token'
    | '/s/reel/$token'
    | '/match/$matchId/insights'
    | '/match/$matchId/match'
    | '/match/$matchId/reel'
    | '/match/$matchId/session'
    | '/match/$matchId/stats'
    | '/match/$matchId/story'
    | '/match/$matchId/territory'
    | '/match/$matchId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/glossary'
    | '/reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/upload'
    | '/library'
    | '/new'
    | '/onboarding'
    | '/processing'
    | '/signup/club'
    | '/signup/ready'
    | '/signup/team'
    | '/upload/processing'
    | '/settings/account'
    | '/settings/club'
    | '/settings/profile'
    | '/s/player/$token'
    | '/s/reel/$token'
    | '/match/$matchId/insights'
    | '/match/$matchId/match'
    | '/match/$matchId/reel'
    | '/match/$matchId/session'
    | '/match/$matchId/stats'
    | '/match/$matchId/story'
    | '/match/$matchId/territory'
    | '/match/$matchId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/glossary'
    | '/reset'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/upload'
    | '/_authenticated/library'
    | '/_authenticated/new'
    | '/_authenticated/onboarding'
    | '/_authenticated/processing'
    | '/signup_/club'
    | '/signup_/ready'
    | '/signup_/team'
    | '/upload_/processing'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/club'
    | '/_authenticated/settings/profile'
    | '/s/player/$token'
    | '/s/reel/$token'
    | '/_authenticated/match/$matchId/insights'
    | '/_authenticated/match/$matchId/match'
    | '/_authenticated/match/$matchId/reel'
    | '/_authenticated/match/$matchId/session'
    | '/_authenticated/match/$matchId/stats'
    | '/_authenticated/match/$matchId/story'
    | '/_authenticated/match/$matchId/territory'
    | '/_authenticated/match/$matchId/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  GlossaryRoute: typeof GlossaryRoute
  ResetRoute: typeof ResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  SignupClubRoute: typeof SignupClubRoute
  SignupReadyRoute: typeof SignupReadyRoute
  SignupTeamRoute: typeof SignupTeamRoute
  UploadProcessingRoute: typeof UploadProcessingRoute
  SPlayerTokenRoute: typeof SPlayerTokenRoute
  SReelTokenRoute: typeof SReelTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processing': {
      id: '/_authenticated/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AuthenticatedProcessingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/signup_/club': {
      id: '/signup_/club'
      path: '/signup/club'
      fullPath: '/signup/club'
      preLoaderRoute: typeof SignupClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/ready': {
      id: '/signup_/ready'
      path: '/signup/ready'
      fullPath: '/signup/ready'
      preLoaderRoute: typeof SignupReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/team': {
      id: '/signup_/team'
      path: '/signup/team'
      fullPath: '/signup/team'
      preLoaderRoute: typeof SignupTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload_/processing': {
      id: '/upload_/processing'
      path: '/upload/processing'
      fullPath: '/upload/processing'
      preLoaderRoute: typeof UploadProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/club': {
      id: '/_authenticated/settings/club'
      path: '/settings/club'
      fullPath: '/settings/club'
      preLoaderRoute: typeof AuthenticatedSettingsClubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/player/$token': {
      id: '/s/player/$token'
      path: '/s/player/$token'
      fullPath: '/s/player/$token'
      preLoaderRoute: typeof SPlayerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/reel/$token': {
      id: '/s/reel/$token'
      path: '/s/reel/$token'
      fullPath: '/s/reel/$token'
      preLoaderRoute: typeof SReelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/match/$matchId/insights': {
      id: '/_authenticated/match/$matchId/insights'
      path: '/match/$matchId/insights'
      fullPath: '/match/$matchId/insights'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/match': {
      id: '/_authenticated/match/$matchId/match'
      path: '/match/$matchId/match'
      fullPath: '/match/$matchId/match'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdMatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/reel': {
      id: '/_authenticated/match/$matchId/reel'
      path: '/match/$matchId/reel'
      fullPath: '/match/$matchId/reel'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdReelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/session': {
      id: '/_authenticated/match/$matchId/session'
      path: '/match/$matchId/session'
      fullPath: '/match/$matchId/session'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdSessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/stats': {
      id: '/_authenticated/match/$matchId/stats'
      path: '/match/$matchId/stats'
      fullPath: '/match/$matchId/stats'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/story': {
      id: '/_authenticated/match/$matchId/story'
      path: '/match/$matchId/story'
      fullPath: '/match/$matchId/story'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdStoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/territory': {
      id: '/_authenticated/match/$matchId/territory'
      path: '/match/$matchId/territory'
      fullPath: '/match/$matchId/territory'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdTerritoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/match/$matchId/player/$playerId': {
      id: '/_authenticated/match/$matchId/player/$playerId'
      path: '/match/$matchId/player/$playerId'
      fullPath: '/match/$matchId/player/$playerId'
      preLoaderRoute: typeof AuthenticatedMatchMatchIdPlayerPlayerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProcessingRoute: typeof AuthenticatedProcessingRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsClubRoute: typeof AuthenticatedSettingsClubRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedMatchMatchIdInsightsRoute: typeof AuthenticatedMatchMatchIdInsightsRoute
  AuthenticatedMatchMatchIdMatchRoute: typeof AuthenticatedMatchMatchIdMatchRoute
  AuthenticatedMatchMatchIdReelRoute: typeof AuthenticatedMatchMatchIdReelRoute
  AuthenticatedMatchMatchIdSessionRoute: typeof AuthenticatedMatchMatchIdSessionRoute
  AuthenticatedMatchMatchIdStatsRoute: typeof AuthenticatedMatchMatchIdStatsRoute
  AuthenticatedMatchMatchIdStoryRoute: typeof AuthenticatedMatchMatchIdStoryRoute
  AuthenticatedMatchMatchIdTerritoryRoute: typeof AuthenticatedMatchMatchIdTerritoryRoute
  AuthenticatedMatchMatchIdPlayerPlayerIdRoute: typeof AuthenticatedMatchMatchIdPlayerPlayerIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProcessingRoute: AuthenticatedProcessingRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsClubRoute: AuthenticatedSettingsClubRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedMatchMatchIdInsightsRoute:
    AuthenticatedMatchMatchIdInsightsRoute,
  AuthenticatedMatchMatchIdMatchRoute: AuthenticatedMatchMatchIdMatchRoute,
  AuthenticatedMatchMatchIdReelRoute: AuthenticatedMatchMatchIdReelRoute,
  AuthenticatedMatchMatchIdSessionRoute: AuthenticatedMatchMatchIdSessionRoute,
  AuthenticatedMatchMatchIdStatsRoute: AuthenticatedMatchMatchIdStatsRoute,
  AuthenticatedMatchMatchIdStoryRoute: AuthenticatedMatchMatchIdStoryRoute,
  AuthenticatedMatchMatchIdTerritoryRoute:
    AuthenticatedMatchMatchIdTerritoryRoute,
  AuthenticatedMatchMatchIdPlayerPlayerIdRoute:
    AuthenticatedMatchMatchIdPlayerPlayerIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  GlossaryRoute: GlossaryRoute,
  ResetRoute: ResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  SignupClubRoute: SignupClubRoute,
  SignupReadyRoute: SignupReadyRoute,
  SignupTeamRoute: SignupTeamRoute,
  UploadProcessingRoute: UploadProcessingRoute,
  SPlayerTokenRoute: SPlayerTokenRoute,
  SReelTokenRoute: SReelTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
